#!/usr/bin/env python3
"""
embed_assets.py — Embed Swordigo Desktop launcher assets into the binary.

Permanent fix for the recurring "assets go missing from deb/rpm" bug:
instead of relying on disk paths (src/assets/, launcher/, /usr/share/...),
every texture and font used by the launcher / swordfare GUI / ruby viewer is
baked directly into the executable as byte arrays. Runtime loaders check the
embedded table FIRST, so the FontAwesome icons and UI textures always work
regardless of installation layout.

Outputs:
    src/platform/embedded_assets.h    — public API
    src/platform/embedded_assets.cpp  — byte arrays + lookup table

Usage:
    python3 tools/embed_assets.py            # regenerate from src/assets/
    make embed-assets                        # same via Makefile target

The generator intentionally skips src/assets/fonts/static/ (2.3MB of static
font variants) to keep the binary lean. Everything else under src/assets is
embedded.
"""

import os
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
ASSETS_DIR = os.path.join(ROOT, "src", "assets")
OUT_H = os.path.join(ROOT, "src", "platform", "embedded_assets.h")
OUT_CPP = os.path.join(ROOT, "src", "platform", "embedded_assets.cpp")

SKIP_PREFIXES = ("fonts/static",)

# Extensions we actually use. .xml template skipped (not a runtime asset).
KEEP_EXTS = (".png", ".ttf", ".otf", ".jpg", ".jpeg", ".bmp", ".tga")


def collect_files():
    files = []
    for dirpath, dirnames, filenames in os.walk(ASSETS_DIR):
        # Prune skipped subtrees
        dirnames[:] = [d for d in dirnames
                       if not os.path.join(os.path.relpath(dirpath, ASSETS_DIR), d)
                       .startswith(SKIP_PREFIXES)]
        for fn in sorted(filenames):
            if fn.startswith(".") or fn.endswith("~"):
                continue
            full = os.path.join(dirpath, fn)
            rel = os.path.relpath(full, ASSETS_DIR).replace(os.sep, "/")
            if not rel.lower().endswith(KEEP_EXTS):
                continue
            files.append((rel, full))
    files.sort()
    return files


def c_identifier(name):
    keep = "".join(c if (c.isalnum() or c == "_") else "_" for c in name)
    if not keep or keep[0].isdigit():
        keep = "_" + keep
    return keep


def emit_cpp(files):
    out = []
    out.append("// =============================================================================")
    out.append("// embedded_assets.cpp — GENERATED FILE, DO NOT EDIT BY HAND")
    out.append("// Generated by tools/embed_assets.py. All launcher textures & fonts are")
    out.append("// baked into the binary so assets never go missing from deb/rpm packages.")
    out.append("// =============================================================================")
    out.append('#include "platform/embedded_assets.h"')
    out.append("#include <cstring>")
    out.append("")
    out.append("// stb_image lives here (single implementation shared by every consumer).")
    out.append('#define STB_IMAGE_IMPLEMENTATION')
    out.append('#include "stb/stb_image.h"')
    out.append("")
    out.append("namespace {")
    out.append("")

    entries = []
    total = 0
    for rel, full in files:
        ident = "k_" + c_identifier(rel)
        with open(full, "rb") as f:
            data = f.read()
        total += len(data)
        entries.append((rel, ident, len(data)))
        out.append("/* %s (%d bytes) */" % (rel, len(data)))
        out.append("static const unsigned char %s[] = {" % ident)
        # 16 bytes per line keeps the assembler fast and the file compact
        for i in range(0, len(data), 16):
            chunk = data[i:i + 16]
            line = ", ".join("0x%02x" % b for b in chunk)
            out.append("    " + line + ",")
        out.append("};")
        out.append("")

    out.append("struct EmbeddedEntry { const char* name; const unsigned char* data; unsigned int size; };")
    out.append("static const EmbeddedEntry k_entries[] = {")
    for rel, ident, size in entries:
        out.append('    { "%s", %s, %u },' % (rel, ident, size))
    out.append("};")
    out.append("static const unsigned int k_entry_count = %d;" % len(entries))
    out.append("")
    out.append("} // namespace")
    out.append("")

    out.append("bool embedded_asset(const char* name, const unsigned char** data, size_t* size) {")
    out.append("    if (!name || !data || !size) return false;")
    out.append("    if (!name[0]) return false;")
    out.append("    // 1. Exact relative-path match (e.g. \"fonts/fa-solid-900.ttf\")")
    out.append("    for (unsigned int i = 0; i < k_entry_count; i++) {")
    out.append("        if (std::strcmp(k_entries[i].name, name) == 0) {")
    out.append("            *data = k_entries[i].data;")
    out.append("            *size = k_entries[i].size;")
    out.append("            return true;")
    out.append("        }")
    out.append("    }")
    out.append("    // 2. Basename-only match (e.g. \"fa-solid-900.ttf\" or \"ui_panel.png\")")
    out.append("    const char* base = std::strrchr(name, '/');")
    out.append("    base = base ? base + 1 : name;")
    out.append("    for (unsigned int i = 0; i < k_entry_count; i++) {")
    out.append("        const char* entry = k_entries[i].name;")
    out.append("        const char* ebase = std::strrchr(entry, '/');")
    out.append("        ebase = ebase ? ebase + 1 : entry;")
    out.append("        if (std::strcmp(ebase, base) == 0) {")
    out.append("            *data = k_entries[i].data;")
    out.append("            *size = k_entries[i].size;")
    out.append("            return true;")
    out.append("        }")
    out.append("    }")
    out.append("    return false;")
    out.append("}")
    out.append("")
    out.append("// Decode embedded PNG/JPEG bytes into RGBA pixels (stb_image).")
    out.append("// Returns true on success; caller must free *out with asset_image_free().")
    out.append("bool asset_decode_image(const unsigned char* data, size_t size,")
    out.append("                         unsigned char** out, int* w, int* h) {")
    out.append("    if (!data || size < 8 || !out || !w || !h) return false;")
    out.append("    int ch = 0;")
    out.append("    unsigned char* px = stbi_load_from_memory(data, (int)size, w, h, &ch, 4);")
    out.append("    if (!px || *w <= 0 || *h <= 0) { if (px) stbi_image_free(px); return false; }")
    out.append("    *out = px;")
    out.append("    return true;")
    out.append("}")
    out.append("")
    out.append("void asset_image_free(unsigned char* px) {")
    out.append("    if (px) stbi_image_free(px);")
    out.append("}")
    out.append("")
    out.append("bool embedded_asset_has_prefix(const char* prefix) {")
    out.append("    if (!prefix) return false;")
    out.append("    size_t plen = std::strlen(prefix);")
    out.append("    if (plen == 0) return k_entry_count > 0;")
    out.append("    for (unsigned int i = 0; i < k_entry_count; i++) {")
    out.append("        if (std::strncmp(k_entries[i].name, prefix, plen) == 0) return true;")
    out.append("    }")
    out.append("    return false;")
    out.append("}")
    out.append("")

    text = "\n".join(out)
    with open(OUT_CPP, "w") as f:
        f.write(text)
    return len(files), total


def emit_header():
    h = """// =============================================================================
// embedded_assets.h — GENERATED FILE, DO NOT EDIT BY HAND
// Generated by tools/embed_assets.py
//
// Returns the bytes of any launcher texture/font baked into the binary.
// Matching is by relative path first ("icons/ui_panel.png"), then by bare
// filename ("ui_panel.png"). This is the FIRST source the asset loaders try,
// so icons, fonts and textures always load — even from deb/rpm installs.
// =============================================================================

#pragma once
#include <cstddef>

#ifdef __cplusplus
extern "C" {
#endif

// Returns true and fills *data/*size if the named asset is embedded.
bool embedded_asset(const char* name, const unsigned char** data, size_t* size);

// Convenience: does any embedded asset exist under this path prefix
// (e.g. "fonts/")? Cheap linear scan over a small table.
bool embedded_asset_has_prefix(const char* prefix);

// Decode embedded image bytes (PNG/JPEG/...) into RGBA pixels via stb_image.
// Returns true on success; *out must be freed with asset_image_free().
bool asset_decode_image(const unsigned char* data, size_t size,
                        unsigned char** out, int* w, int* h);
void asset_image_free(unsigned char* px);

#ifdef __cplusplus
}
#endif
"""
    with open(OUT_H, "w") as f:
        f.write(h)


def main():
    files = collect_files()
    if not files:
        print("No assets found under %s" % ASSETS_DIR)
        return 1
    count, total = emit_cpp(files)
    emit_header()
    print("Embedded %d assets (%d bytes / %.1f MB) -> %s, %s"
          % (count, total, total / (1024.0 * 1024.0), OUT_CPP, OUT_H))
    return 0


if __name__ == "__main__":
    sys.exit(main())
