// ============================================================================
// launcher_config.cpp — TOML-based persistent launcher configuration.
//
// Format: minimal TOML. No external dependency — hand-written parser/writer
// for the subset we need (sections + key=value + inline arrays of strings).
//
// Sections:
//   [appearance]  accent_r/g/b/a, profile_name, profile_avatar
//   [audio]       master_volume, music_volume, sfx_volume
//   [graphics]    postfx_enabled, pvr_software_decode
//   [loading]     loading_slideshow
//   [mods]        load_order = ["id1", "id2", ...]
//
// ============================================================================

#include "platform/launcher_config.h"
#include "platform/data_path.h"

#include <algorithm>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <sstream>
#include <iostream>

namespace fs = std::filesystem;

// ============================================================================
// Path
// ============================================================================

std::string launcher_config_path() {
    const char* home = getenv("HOME");
    if (!home) home = ".";
    return std::string(home) + "/.config/swordigo-desktop/launcher.toml";
}

// ============================================================================
// Minimal TOML writer
// ============================================================================

static void toml_write_float(FILE* f, const char* key, float v) {
    fprintf(f, "%s = %.4f\n", key, v);
}
static void toml_write_bool(FILE* f, const char* key, bool v) {
    fprintf(f, "%s = %s\n", key, v ? "true" : "false");
}
static void toml_write_str(FILE* f, const char* key, const std::string& v) {
    fprintf(f, "%s = \"%s\"\n", key, v.c_str());
}
static void toml_write_string_array(FILE* f, const char* key,
                                     const std::vector<std::string>& arr) {
    fprintf(f, "%s = [", key);
    for (size_t i = 0; i < arr.size(); i++) {
        if (i > 0) fprintf(f, ", ");
        fprintf(f, "\"%s\"", arr[i].c_str());
    }
    fprintf(f, "]\n");
}

bool launcher_config_save(const LauncherConfig& cfg) {
    std::string path = launcher_config_path();
    // Create parent directory
    fs::create_directories(fs::path(path).parent_path());

    FILE* f = fopen(path.c_str(), "w");
    if (!f) {
        std::cerr << "[LauncherConfig] Failed to write " << path << std::endl;
        return false;
    }

    fprintf(f, "# Swordigo Desktop — launcher configuration\n");
    fprintf(f, "# Generated by Swordfare. Edit with care.\n\n");

    // [appearance]
    fprintf(f, "[appearance]\n");
    toml_write_float(f, "accent_r", cfg.accent_r);
    toml_write_float(f, "accent_g", cfg.accent_g);
    toml_write_float(f, "accent_b", cfg.accent_b);
    toml_write_float(f, "accent_a", cfg.accent_a);
    toml_write_str(f, "profile_name", cfg.profile_name);
    toml_write_str(f, "profile_avatar", cfg.profile_avatar);
    fprintf(f, "\n");

    // [audio]
    fprintf(f, "[audio]\n");
    toml_write_float(f, "master_volume", cfg.master_volume);
    toml_write_float(f, "music_volume", cfg.music_volume);
    toml_write_float(f, "sfx_volume", cfg.sfx_volume);
    fprintf(f, "\n");

    // [graphics]
    fprintf(f, "[graphics]\n");
    toml_write_bool(f, "postfx_enabled", cfg.postfx_enabled);
    toml_write_bool(f, "pvr_software_decode", cfg.pvr_software_decode);
    fprintf(f, "\n");

    // [loading]
    fprintf(f, "[loading]\n");
    toml_write_bool(f, "loading_slideshow", cfg.loading_slideshow);
    fprintf(f, "\n");

    // [mods]
    fprintf(f, "# VFS mod load order. Top = highest override priority.\n");
    fprintf(f, "[mods]\n");
    toml_write_string_array(f, "load_order", cfg.mod_load_order);

    fclose(f);
    std::cout << "[LauncherConfig] Saved to " << path << std::endl;
    return true;
}

// ============================================================================
// Minimal TOML reader (sections + key=value + inline string arrays)
// ============================================================================

struct TomlReader {
    std::string section;
    LauncherConfig cfg;

    void handle_line(const std::string& line) {
        // Trim whitespace
        size_t s = line.find_first_not_of(" \t\r");
        if (s == std::string::npos) return;
        std::string l = line.substr(s);
        if (l.empty() || l[0] == '#') return;

        // Section header [name]
        if (l[0] == '[') {
            size_t end = l.find(']');
            section = (end != std::string::npos) ? l.substr(1, end - 1) : l.substr(1);
            return;
        }

        // key = value
        size_t eq = l.find('=');
        if (eq == std::string::npos) return;

        std::string key = l.substr(0, eq);
        key.erase(key.find_last_not_of(" \t") + 1);

        std::string val = l.substr(eq + 1);
        val.erase(0, val.find_first_not_of(" \t"));
        val.erase(val.find_last_not_of(" \t\r") + 1);

        // Strip quotes
        if (val.size() >= 2 && val.front() == '"' && val.back() == '"') {
            val = val.substr(1, val.size() - 2);
        }

        // Dispatch
        if (section == "appearance") {
            if (key == "accent_r") cfg.accent_r = (float)atof(val.c_str());
            else if (key == "accent_g") cfg.accent_g = (float)atof(val.c_str());
            else if (key == "accent_b") cfg.accent_b = (float)atof(val.c_str());
            else if (key == "accent_a") cfg.accent_a = (float)atof(val.c_str());
            else if (key == "profile_name") cfg.profile_name = val;
            else if (key == "profile_avatar") cfg.profile_avatar = val;
        } else if (section == "audio") {
            if (key == "master_volume") cfg.master_volume = (float)atof(val.c_str());
            else if (key == "music_volume") cfg.music_volume = (float)atof(val.c_str());
            else if (key == "sfx_volume") cfg.sfx_volume = (float)atof(val.c_str());
        } else if (section == "graphics") {
            if (key == "postfx_enabled") cfg.postfx_enabled = (val == "true");
            else if (key == "pvr_software_decode") cfg.pvr_software_decode = (val == "true");
        } else if (section == "loading") {
            if (key == "loading_slideshow") cfg.loading_slideshow = (val == "true");
        } else if (section == "mods") {
            if (key == "load_order") {
                cfg.mod_load_order.clear();
                // Parse inline array: ["id1", "id2"]
                size_t start = val.find('[');
                size_t end = val.find(']');
                if (start != std::string::npos && end != std::string::npos) {
                    std::string inner = val.substr(start + 1, end - start - 1);
                    std::istringstream iss(inner);
                    std::string token;
                    while (std::getline(iss, token, ',')) {
                        token.erase(0, token.find_first_not_of(" \t\""));
                        token.erase(token.find_last_not_of(" \t\"") + 1);
                        if (!token.empty()) cfg.mod_load_order.push_back(token);
                    }
                }
            }
        }
    }
};

LauncherConfig launcher_config_load() {
    LauncherConfig cfg;
    std::string path = launcher_config_path();

    std::ifstream f(path);
    if (!f.is_open()) {
        std::cout << "[LauncherConfig] No config found at " << path << " — using defaults" << std::endl;
        return cfg;
    }

    TomlReader reader;
    std::string line;
    while (std::getline(f, line)) {
        reader.handle_line(line);
    }
    cfg = reader.cfg;
    std::cout << "[LauncherConfig] Loaded from " << path
              << " — mods in load order: " << cfg.mod_load_order.size() << std::endl;
    return cfg;
}

// ============================================================================
// Mod load order helpers
// ============================================================================

bool launcher_config_is_mod_enabled(const LauncherConfig& cfg, const std::string& mod_id) {
    for (const auto& id : cfg.mod_load_order)
        if (id == mod_id) return true;
    return false;
}

bool launcher_config_enable_mod(LauncherConfig& cfg, const std::string& mod_id) {
    if (launcher_config_is_mod_enabled(cfg, mod_id)) return false;
    cfg.mod_load_order.insert(cfg.mod_load_order.begin(), mod_id); // top = highest priority
    return true;
}

bool launcher_config_disable_mod(LauncherConfig& cfg, const std::string& mod_id) {
    for (auto it = cfg.mod_load_order.begin(); it != cfg.mod_load_order.end(); ++it) {
        if (*it == mod_id) {
            cfg.mod_load_order.erase(it);
            return true;
        }
    }
    return false;
}

bool launcher_config_reorder_mod(LauncherConfig& cfg, const std::string& mod_id, int delta) {
    std::cout << "[LauncherConfig] reorder: id='" << mod_id << "' delta=" << delta
              << " load_order=[";
    for (int j = 0; j < (int)cfg.mod_load_order.size(); j++)
        std::cout << (j ? ", " : "") << cfg.mod_load_order[j];
    std::cout << "]" << std::endl;
    for (int i = 0; i < (int)cfg.mod_load_order.size(); i++) {
        if (cfg.mod_load_order[i] == mod_id) {
            int new_i = i + delta;
            if (new_i < 0 || new_i >= (int)cfg.mod_load_order.size()) {
                std::cout << "[LauncherConfig] reorder FAILED: i=" << i << " new_i=" << new_i << std::endl;
                return false;
            }
            std::swap(cfg.mod_load_order[i], cfg.mod_load_order[new_i]);
            std::cout << "[LauncherConfig] reorder OK: swapped i=" << i << " <-> new_i=" << new_i << std::endl;
            return true;
        }
    }
    std::cout << "[LauncherConfig] reorder FAILED: id not found" << std::endl;
    return false;
}

const std::string& launcher_config_get_mod_at(const LauncherConfig& cfg, int index) {
    static const std::string empty;
    if (index < 0 || index >= (int)cfg.mod_load_order.size()) return empty;
    return cfg.mod_load_order[index];
}

int launcher_config_mod_count(const LauncherConfig& cfg) {
    return (int)cfg.mod_load_order.size();
}
